--tính tổng giá trị gốc (bảng phiếu thanh toán)
CREATE TRIGGER [dbo].[trg_TongGiaTriGoc]
   ON  [dbo].[SANPHAMCHON] 
   AFTER INSERT, UPDATE
AS 
BEGIN
	DECLARE @maphieu AS NVARCHAR(10) = (SELECT Inserted.MAPHIEU FROM Inserted);
    UPDATE dbo.PHIEUTHANHTOAN SET TONGGIATRIGOC=(SELECT SUM(GIATRITHANHTOAN * SOLUONG) FROM dbo.[SANPHAMCHON] WHERE MAPHIEU = @maphieu AND CONTRONGGIOHANG = 1) WHERE PHIEUTHANHTOAN.MAPHIEU = @maphieu
END


GO

--tính tổng giá trị cần thanh toán (bảng phiếu thanh toán)
CREATE TRIGGER dbo.trg_TongGiaTriCanThanhToan
	ON dbo.SANPHAMCHON
	AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE @maphieu AS NVARCHAR(10) = (SELECT Inserted.MAPHIEU FROM Inserted);
	UPDATE dbo.PHIEUTHANHTOAN SET TONGGIATRICANTHANHTOAN = TONGGIATRIGOC + GIAVANCHUYEN WHERE MAPHIEU = @maphieu
END


GO


--tính giá trị thanh toán (bảng sản phẩm chọn)
CREATE TRIGGER dbo.trg_GiaTriThanhToan
	ON dbo.SANPHAMCHON
	AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE @mavoucher AS NVARCHAR(10) = (SELECT Inserted.MAVOUCHER FROM Inserted);
	IF @mavoucher IS NULL
		BEGIN
        	UPDATE dbo.SANPHAMCHON SET GIATRITHANHTOAN = Inserted.GIAGOC FROM Inserted WHERE Inserted.MATAIKHOAN = dbo.SANPHAMCHON.MATAIKHOAN AND Inserted.STT = dbo.SANPHAMCHON.STT
			RETURN
        END
	DECLARE @min_hang AS INT  = (SELECT SOHANGTOITHIEU FROM dbo.VOUCHERSHOP WHERE dbo.VOUCHERSHOP.MAVOUCHER = @mavoucher)
	DECLARE @min_tien AS FLOAT  = (SELECT SOTIENTOITHIEUYEUCAU FROM dbo.VOUCHERSHOP WHERE dbo.VOUCHERSHOP.MAVOUCHER = @mavoucher)
	IF ((SELECT GIAGOC * SOLUONG FROM Inserted) >= @min_tien AND (SELECT soluong FROM Inserted) >= @min_hang) 
		BEGIN
			IF ((SELECT SOTIENGIAM FROM dbo.VOUCHERSHOP) IS NULL)
				BEGIN
					UPDATE dbo.SANPHAMCHON SET GIATRITHANHTOAN = dbo.SANPHAMCHON.GIAGOC*(1 - PHANTRAMGIAM /100) FROM dbo.VOUCHER, Inserted WHERE dbo.SANPHAMCHON.MATAIKHOAN = Inserted.MATAIKHOAN AND Inserted.STT = dbo.SANPHAMCHON.STT
					RETURN 
				END
			IF ((SELECT PHANTRAMGIAM FROM dbo.VOUCHERSHOP) IS NULL)
				BEGIN
					UPDATE dbo.SANPHAMCHON SET GIATRITHANHTOAN = (dbo.SANPHAMCHON.GIAGOC - SOTIENGIAM) * dbo.SANPHAMCHON.SOLUONG FROM dbo.VOUCHERSHOP, Inserted WHERE dbo.SANPHAMCHON.MATAIKHOAN = Inserted.MATAIKHOAN AND Inserted.STT = dbo.SANPHAMCHON.STT
					RETURN
				END
        END
END


GO


--tính tổng giá vận chuyển của 1 phiếu (bảng PHIEUTHANHTOAN)
CREATE TRIGGER dbo.trg_GIAVANCHUYEN
	 ON dbo.SANPHAMCHON
	 AFTER INSERT, UPDATE	
AS
BEGIN
	DECLARE @mamathang AS NVARCHAR(10) = (SELECT Inserted.MAMATHANG FROM Inserted)
	DECLARE @maphieu AS NVARCHAR(10) = (SELECT Inserted.MAPHIEU FROM Inserted)
	DECLARE @tienvc AS FLOAT = (SELECT DONVIVANCHUYEN.GIATHANHMOTDONVI
								FROM dbo.DONVIVANCHUYEN, Inserted
								WHERE dbo.DONVIVANCHUYEN.MADONVI = Inserted.DONVIVANCHUYEN
								)
	DECLARE @khoiluong AS FLOAT = (	SELECT dbo.MATHANG.KHOILUONGDONGGOI
									FROM dbo.MATHANG
									WHERE dbo.MATHANG.MAMATHANG = @mamathang
									)
	UPDATE dbo.PHIEUTHANHTOAN SET GIAVANCHUYEN = @tienvc * @khoiluong WHERE dbo.PHIEUTHANHTOAN.MAPHIEU = @maphieu
END

GO

CREATE TRIGGER dbo.trg_DONVIVANCHUYEN
	ON dbo.SANPHAMCHON
	AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @donvivc AS NVARCHAR(10) = (SELECT Inserted.DONVIVANCHUYEN FROM Inserted)
	DECLARE @mamathang AS NVARCHAR(10) = (SELECT Inserted.MAMATHANG FROM Inserted)
	DECLARE q CURSOR FOR
		SELECT dbo.VAN_CHUYEN_MAT_HANG.MADONVI
		FROM dbo.VAN_CHUYEN_MAT_HANG
		WHERE dbo.VAN_CHUYEN_MAT_HANG.MAMATHANG = @mamathang
	DECLARE @dvvc AS NVARCHAR(10)
	OPEN q
	FETCH NEXT FROM q INTO @dvvc
	WHILE @@FETCH_STATUS =0
	BEGIN
		IF(@donvivc = @dvvc)
			RETURN
		FETCH NEXT FROM q INTO @dvvc
	END
	CLOSE q
	DEALLOCATE q
	ROLLBACK
END

GO
